# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Jinrun Yang, Junchi Ren

all: test 
clean: 
	rm -rf test_ch422g        
test: 
	loongarch64-linux-gnu-gcc -lpthread -O2 test_ch422g.c -o test_ch422g 



