# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Junchi Ren, Jinrun Yang

all: test 
clean: 
	rm can_server can_client        
test: 
	loongarch64-linux-gnu-gcc -O2 can_server.c -o can_server 
	loongarch64-linux-gnu-gcc -O2 can_client.c -o can_client



