# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Jinrun Yang, Junchi Ren

all: test 
clean: 
	rm -rf test_motor        
test: 
	loongarch64-linux-gnu-gcc -O2 test_motor.c -o test_motor 



