# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Junchi Ren, Jinrun Yang

all: test 
clean: 
	rm -rf keyinputApp        
test: 
	loongarch64-linux-gnu-gcc -O2 keyinputApp.c -o keyinputApp



