# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Jinrun Yang, Junchi Ren

all: test 
clean: 
	rm -rf test_beep        
test: 
	loongarch64-linux-gnu-gcc -O2 test_beep.c -o test_beep 



