# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Junchi Ren, Jinrun Yang

all: test 
clean: 
	rm -rf test_led        
test: 
	loongarch64-linux-gnu-gcc -O2 test_led.c -o test_led 



