# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Jinrun Yang, Junchi Ren

all: test 
clean: 
	rm -rf test_aht20        
test: 
	loongarch64-linux-gnu-gcc -O2 test_aht20.c -o test_aht20 



