# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Jinrun Yang, Junchi Ren

all: test 
clean: 
	rm -rf test_rc522        
test: 
	loongarch64-linux-gnu-gcc -O2 test_rc522.c -o test_rc522 



