# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Jinrun Yang, Junchi Ren

all: test 
clean: 
	rm -rf test_ms1112      
test: 
	loongarch64-linux-gnu-gcc -O2 test_ms1112.c -o test_ms1112



