# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Jinrun Yang, Junchi Ren

all: test 
clean: 
	rm -rf testStk8ba        
test: 
	loongarch64-linux-gnu-gcc -O2 testStk8ba.c -o testStk8ba 



