# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Jinrun Yang, Junchi Ren

all: test 
clean: 
	rm -rf testMs5541        
test: 
	loongarch64-linux-gnu-gcc -O2 testMs5541.c -o testMs5541 -lm
