# Copyright (c) 2023 Shandong University
# Copyright (c) 2023 Junchi Ren, Jinrun Yang

all: test
clean: 
	rm -rf test_aip        
test: 
	loongarch64-linux-gnu-gcc -O2 test_aip.c -o test_aip -I../kernel_module/



